[workspace]
members = [
    "bsky",
    "scrape_devto",
    "scrape_lobsters",
    "scrape_reddit",
    "twir-bot",
]
resolver = "2"

[workspace.dependencies]
chrono = "0.4"
serde_json = "1.0"
tokio = "1"
tracing = "0.1"
