[package]
name = "bsky"
version = "0.1.0"
edition = "2024"

[lib]
name = "bsky"
path = "src/lib.rs"

[[bin]]
name = "bsky"
path = "src/bin/main.rs"

[dependencies]
atrium-api = "0.25.2"
bsky-sdk = "0.1.18"
regex = "1.11.1"
thiserror = "1"
tokio = { workspace = true, features = ["full"] }
