name: CD

on:
  push:
    branches: [ 'master' ]

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/extrawurst/twir-bot

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: build
      run: |
        cargo b --release
    - name: rename
      run: |
        mv target/release/twir-bot bin/server
    - 
      name: size
      run: ls -l bin/server  
    - 
      name: Build image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
    - 
      name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin
    - 
      name: Push image
      run: |
        docker push $IMAGE_NAME:latest
    -
      name: Redeploy ECS
      run: |
        cd scripts
        ./redeploy.sh ${{ secrets.AWS_KEY }} ${{ secrets.AWS_SECRET }}