name: CI

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Restore cargo cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: "stable"
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - name: check
      run: |
        cargo c
    - name: build
      run: |
        cargo b
    - name: clippy
      run: |
        cargo clippy
    - name: test
      run: |
        cargo t

  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Restore cargo cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: "stable"
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - run: cargo fmt -- --check
    - name: cargo-sort
      run: |
        cargo install cargo-sort --force
        cargo sort -c -w
