name: CI

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
    - name: check
      run: |
        cargo c
    - name: build
      run: |
        cargo b
    - name: clippy
      run: |
        cargo clippy
    - name: test
      run: |
        cargo t

  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: release
      run: |
        cargo b --release
        mkdir bin
        mv target/release/twir-bot bin/server
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: extrawurst/twir-bot:latest

  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt
    - run: cargo fmt -- --check
    - name: cargo-sort
      run: |
        cargo install cargo-sort --force
        cargo sort -c -w